apiVersion: v1
kind: Namespace
metadata:
  name: devopstest
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: devopstest
spec:
  type: ClusterIP
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
---
apiVersion: v1
kind: Endpoints
metadata:
  name: localstack
  namespace: devopstest
subsets:
  - addresses:
      - ip: 217.154.194.174
    ports:
      - name: edge
        port: 4566
        protocol: TCP
